version: '3.8'

services:
  api:
    container_name: axon-backend
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

networks:
  my-network:
    external: true

